name       : gnome-characters
version    : '43.1'
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-characters/43/gnome-characters-43.1.tar.xz : b23e15d950978b363c81a47261ee1a3b47db3c6697ee169ff213eea6572a7841
homepage   : https://apps.gnome.org/app/org.gnome.Characters/
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : Character map application
description: |
    Characters is a simple utility application to find and insert unusual characters. It allows you to quickly find the character you are looking for by searching for keywords. You can also browse characters by categories, such as Punctuation, Pictures, etc.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - libunistring-devel
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
