name       : gnome-characters
version    : '43.0'
release    : 8
source     :
    - https://download.gnome.org/sources/gnome-characters/43/gnome-characters-43.0.tar.xz : a685b9cbf93545ed391168c41c9d8bf83785abbfb489675827ee7342471baac8
homepage   : https://apps.gnome.org/app/org.gnome.Characters/
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : Character map application
description: |
    Characters is a simple utility application to find and insert unusual characters. It allows you to quickly find the character you are looking for by searching for keywords. You can also browse characters by categories, such as Punctuation, Pictures, etc.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - libunistring-devel
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
