name       : gnome-characters
version    : '42.0'
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-characters/42/gnome-characters-42.0.tar.xz : 5da0ffb816f8a6b44f303744ca827a34080118c1c938d8d79af17b7fe67980f8
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : A simple utility application to find and insert unusual characters.
description: |
    A simple utility application to find and insert unusual characters.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(pango)
    - libunistring-devel
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
