name       : gnome-characters
version    : 3.28.2
release    : 3
source     :
    - https://download.gnome.org/sources/gnome-characters/3.28/gnome-characters-3.28.2.tar.xz : 8016f974f4fcdd207f1a3784b2e82c66ebe62451ced0d03fd3bc181e87b0d512
license    :
    - BSD-3-Clause
    - GPL-2.0
component  : multimedia.graphics
summary    : A simple utility application to find and insert unusual characters.
description: |
    A simple utility application to find and insert unusual characters.
builddeps  :
    - pkgconfig(gjs-1.0)
rundeps    :
    - gjs
setup      : |
    %configure --disable-static --enable-doctail
build      : |
    %make
install    : |
    %make_install
