name       : gnome-characters
version    : '41.0'
release    : 6
source     :
    - https://download.gnome.org/sources/gnome-characters/41/gnome-characters-41.0.tar.xz : e129eca93d0099490bc2bfe6437e685fd9855e264b32fb918c0e58ee6aac867b
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : A simple utility application to find and insert unusual characters.
description: |
    A simple utility application to find and insert unusual characters.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(pango)
    - libunistring-devel
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
