name       : gnome-characters
version    : '44.0'
release    : 10
source     :
    - https://download.gnome.org/sources/gnome-characters/44/gnome-characters-44.0.tar.xz : 05b15c028cc190aef92e6092fd84fa8d5f2448e0e9076446a3566f3a081ff50b
homepage   : https://apps.gnome.org/app/org.gnome.Characters/
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : multimedia.graphics
summary    : Character map application
description: |
    Characters is a simple utility application to find and insert unusual characters. It allows you to quickly find the character you are looking for by searching for keywords. You can also browse characters by categories, such as Punctuation, Pictures, etc.
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - libunistring-devel
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
